# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/12b71446-5252-4b8f-a1b9-954393b02549";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-195ba821-6494-47db-b21e-c6285026518b".device = "/dev/disk/by-uuid/195ba821-6494-47db-b21e-c6285026518b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A9C-DA71";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/22c9280b-ce58-4753-9fbf-35bb95512826"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp59s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp64s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  # See: https://nixos.wiki/wiki/Intel_Graphics
  # And: https://nixos.wiki/wiki/Accelerated_Video_Playback
  # For the source of this config
  # iHD doesn't use the GPU, but i965 does 
  # accoring to testing intel_gpu_top from pkgs.intel-gpu-tools
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      # intel-media-driver # LIBVA_DRIVER_NAME=iHD
      intel-vaapi-driver # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
      libvdpau-va-gl

      # vpl-gpu-rt          # for newer GPUs on NixOS >24.05 or unstable
      # onevpl-intel-gpu  # for newer GPUs on NixOS <= 24.05
      intel-media-sdk   # for older GPUs
    ];
  };
  
  # Force intel-media-driver or intel-vaapi-driver
  environment.sessionVariables = { LIBVA_DRIVER_NAME = "i965"; }; 
}
