# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-386e8169-a9fe-44e6-af0a-513e9cdc1356";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-386e8169-a9fe-44e6-af0a-513e9cdc1356".device = "/dev/disk/by-uuid/386e8169-a9fe-44e6-af0a-513e9cdc1356";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9586-AFB6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    zramSwap = {
      enable = true;
      memoryPercent = 25;
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # # Load libva driver for accelerated video
  # nixpkgs.config.packageOverrides = pkgs: {
  #   intel-vaapi-driver = pkgs.intel-vaapi-driver.override { enableHybridCodec = true; };
  # };

  # See: https://nixos.wiki/wiki/Intel_Graphics
  # And: https://nixos.wiki/wiki/Accelerated_Video_Playback
  # For the source of this config
  # iHD doesn't use the GPU, but i965 does
  # accoring to testing intel_gpu_top from pkgs.intel-gpu-tools
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # LIBVA_DRIVER_NAME=iHD
      # intel-vaapi-driver # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
      # libvdpau-va-gl

      # vpl-gpu-rt          # for newer GPUs on NixOS >24.05 or unstable
      # intel-media-sdk   # for older GPUs
    ];
    # extraPackages32 = with pkgs.pkgsi686Linux; [ intel-vaapi-driver ];
  };


  # Force intel-media-driver or intel-vaapi-driver
  environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; };

  # environment.variables = {
  #   VDPAU_DRIVER = "va_gl";
  # };

  services.fstrim.enable = true;
  services.thermald.enable = true;
  services.power-profiles-daemon.enable = true;
}
